### ISSUE TITLE
MainKt run function opens invisible window.

### ISSUE THREAD

**Issue by wnuke** [kami-blue/bot-kt#25]
When run in the dev environment an invisible window called MainKt is opened, this probably shouldn't happen as it is annoying while testing due to focus switches. (using macOS)

**Comment by dominikaaaa** [comment]
This doesn't happen on Linux. Sounds like an issue specific to your environment. Send a screenshot of your run configuration.

**Comment by wnuke** [comment]
<img width="725" alt="Screen Shot 2020-09-08 at 12 24 20" src="https://user-images.githubusercontent.com/17758796/92519069-3b612280-f1ce-11ea-9314-3a0793db94da.png">
I am assuming you mean the IntelliJ Idea one so here it is, I also tested, and this only happens in dev env, running java -jar does not do this.

**Comment by dominikaaaa** [comment]
![image](https://user-images.githubusercontent.com/17222512/92519329-c4388800-f1e7-11ea-8dba-ce4bd5919b9e.png)
Doesn't happen to me, and it shouldn't. I'm going to close this as it's probably an Intellij IDEA bug

**Comment by wnuke** [comment]
This is actually not an IDE bug, I just tested, my cli java is set to 14, if I use java 8 in cli then it opens the window.

**Comment by dominikaaaa** [comment]
That's a Kotlin bug or something to do with how it launches binaries then.
