### ISSUE TITLE
Refactor ShutDown to ShutDownCommand

### ISSUE THREAD

**Issue by sourTaste000** [kami-blue/bot-kt#28]

**Comment by dominikaaaa** [comment]
I already did this though

**Comment by sourTaste000** [comment]
![image](https://user-images.githubusercontent.com/47074495/93010910-3097ec00-f546-11ea-986f-92f9b322cd96.png)
Still shows as ShutDown to me

**Comment by dominikaaaa** [comment]
because I haven't pushed

**Comment by dominikaaaa** [comment]
I did it a few days ago
