### ISSUE TITLE
Emotes for ;userinfo

### ISSUE THREAD

**Issue by SoNothingMC** [kami-blue/bot-kt#360]
**Is your feature request related to a problem? Please describe.**
I miss the bot-js emotes.

![image](https://user-images.githubusercontent.com/32032824/103059682-c7158800-45e0-11eb-94b2-1293cd1774ca.jpeg)
*bot-kt, currently*

**Describe the solution you'd like**
I would like to see the emotes back onto ;userinfo like this:

![image](https://user-images.githubusercontent.com/32032824/103059735-f0361880-45e0-11eb-9f83-d8f419730fb1.png)
*bot-js*

**Comment by l1ving** [comment]
I'd rather not have hardcoded emojis that somebody has to provide somewhere.

**Comment by SoNothingMC** [comment]
It's alright 👍
