### ISSUE TITLE
support launchd

### ISSUE THREAD

**Issue by sourTaste000** [kami-blue/bot-kt#42]
macos moment

**Comment by wnuke** [comment]
When do you actively use your mac as a server?
Or when do you run macOS on a server machine...

**Comment by sourTaste000** [comment]
self host

**Comment by wnuke** [comment]
It still doesn't make sense, it would be much better to buy a raspi zero and host on there, but I guess there is a very niche and strange use case for this...

**Comment by l1ving** [comment]
Mac's support systemd

**Comment by sourTaste000** [comment]
<img width="1092" alt="Screen Shot 2020-09-28 at 1 27 11 PM" src="https://user-images.githubusercontent.com/47074495/94482556-52bc7b80-018e-11eb-97d6-95ff6ad0aa64.png">

**Comment by sourTaste000** [comment]
https://unix.stackexchange.com/questions/411501/can-i-install-systemctl-onto-my-mac

**Comment by wnuke** [comment]
systemctl != systemd though right?

**Comment by sourTaste000** [comment]
yes

**Comment by l1ving** [comment]
systemctl is only an interface to configure systemd
