### ISSUE TITLE
Last three fields for the pr's embed broken

### ISSUE THREAD

**Issue by sourTaste000** [kami-blue/bot-kt#46]
**Describe the bug**
The last three fields for the pr embed doesn't work(IssueCommand).

**To Reproduce**
1. Type `;issue <any repo> <pr's num that made changes>`

**Expected behavior**
Expected to list the addition, deletion, commits and changed files correctly.

**Screenshots**
![2020-10-03-11-48-43](https://user-images.githubusercontent.com/47074495/94999491-91777a80-056e-11eb-8657-bc9568a64cb2.png)

**Additional context**
Maybe its the discussion api's problem? [here](https://github.com/l1ving/github-discussion-api/)

**Comment by l1ving** [comment]
Lol I just removed them, too lazy to fix
