### ISSUE TITLE
Port starboard here

### ISSUE THREAD

**Issue by sourTaste000** [kami-blue/bot-kt#65]
**Is your feature request related to a problem? Please describe.**
js bad

**Describe the solution you'd like**
port the starboard feature of js bot here

**Comment by sourTaste000** [comment]
bruh kordis doesn't even support reactions

**Comment by l1ving** [comment]
@sourTaste000 ![Screenshot_20201028-192217.png](https://user-images.githubusercontent.com/17222512/97507120-ebdbdf00-1952-11eb-8010-d18f6881c38c.png)

**Comment by sourTaste000** [comment]
can't check how many reactions??

**Comment by l1ving** [comment]
No. I can add that functionality if you want

**Comment by sourTaste000** [comment]
ill add it

**Comment by l1ving** [comment]
https://discord.com/developers/docs/topics/gateway

The docs don't say that you can get all the reactions. I think stuff like discord-js caches it with an event/

**Comment by l1ving** [comment]
https://discord.com/developers/docs/resources/channel#get-reactions

**Comment by l1ving** [comment]
Nevermind

**Comment by l1ving** [comment]
Added get and remove reactions

**Comment by sourTaste000** [comment]
you still cannot get message content from the reaction

**Comment by l1ving** [comment]
No, that's just a kordis meme. Switching to JDA eventually

**Comment by Xiaro** [comment]
Imagine not reading the code

**Comment by Xiaro** [comment]
closed in #357
